export const MOVIES_ADD_FAVORITE = 'MOVIES_ADD_FAVORITE';
export const MOVIES_REMOVE_FAVORITE = 'MOVIES_REMOVE_FAVORITE';
export const MOVIES_GET = 'MOVIES_GET';
export const MOVIES_GET_DETAIL = 'MOVIES_GET_DETAIL';
export const MOVIES_GET_FAILURE = 'MOVIES_GET_FAILURE';
export const MOVIES_GET_DETAIL_FAILURE = 'MOVIES_GET_FAILURE';
export const apiKey = '69ff54fa';

/* 
export const MOVIES_GET_REQUEST = 'MOVIES_GET_REQUEST';
export const MOVIES_GET_SUCCESS = 'MOVIES_GET_SUCCESS';
*/